### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by JustJoostNL** [Joery-M/Govee-LAN-Control#6]
Hey @Joery-M! I have some issues when using the library in my Electron app, I am using the following code:

```ts
import Govee from 'govee-lan-control'

export default async function goveeInitialize(){
    let theGovee;
    try {
        theGovee = new Govee();
    } catch (error) {
        console.log(error);
    }
    theGovee.on("ready", () => {
        console.log('ready!')
    });
    theGovee.on("deviceAdded", (device) => {
        console.log("Govee device found: " + device.model);
    });
}
```

I have the following issues when using this:

- It doesn't log "ready", maybe the event is not fired?
- It doesn't log my devices, I already checked multiple times if "Lan Control" is enabled, and it is.
- I also got the following error: `UDP Socket was not established whilst trying to discover new devices. Is the server able to access UDP port 4001 and 4002 on address 239.255.255.250?`. I tried to open up my firewall, but this didn't help.

Any idea how I can fix this?

I really appreciate your work!

Thanks in advance!

**Comment by JustJoostNL** [comment]
Oh and btw, I use version V3.0.0.

**Comment by csinatsch** [comment]
I am also having this issue

**Comment by Joery-M** [comment]
Unfortunately UDP is one of those "if it works, it works, if it doesn't, good luck" things.

This error message appears when there is no response to the ping command on any network interface.

This can mean a couple of things.
- LAN Control has not been enabled in the app
- There's a network setting on your switch or router blocking the request (or response)
- The port is already taken

One troubleshooting step you can do is run dgramTest.js in the src folder to find where the issue is.

**Comment by JustJoostNL** [comment]
Just tried it again, and it works now. (didn't change anything). So I'll close this.
